markdown: kramdown
highlighter: rouge

# Site wide configuration

description       : Blog
title             : Günlük Yazılar
keywords          : Blog, Günce, Yazılar
logo              : siteicon.png
search            : false
baseurl           : ""
url               : https://vdemir.github.io
author:
  name            : "Günce"
  url             : https://vdemir.github.io
  email           : jeruselam@yandex.com
  bio             : "Just another tattooed, time traveling designer."
  picture         : ""

yandex-verify     : "b642748cb18cbd1c"
google-verify     : "zFuwF6tlf7YemTRN-ZOvl5lG1rjuI9qEomPbr_5vAu8"


comments:
  provider: "disqus"
  disqus:
    shortname: "vdemir-github-io"

social:
  type:  # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/zekid800"
    - "https://facebook.com/zekid800"
    - "https://instagram.com/zekid800"
    - "https://www.linkedin.com/in/zekid800"
    - "https://plus.google.com/zekid800"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-1234567-8"
    anonymize_ip: false # default


