timezone:       Europe/Istanbul
locale:         tr_TR 
name:           "vdemir.github.io"
description:    "Pisi Linux Blogger"
icon:           /assets/icon.png
comments: True



markdown: rdiscount
highlighter: pygments
