name: Vedat Demir
description: Pisi Linux Developer
avatar: https://avatars1.githubusercontent.com/u/7329803?v=3&s=460
footer-links:
    email: vedat@pisilinux.org
    github: vdemir
markdown: rdiscount
highlighter: pygments
